version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  next:
    image: node:14
    ports:
      - '3000:3000'
    volumes:
      - .:/srv/web:rw
    working_dir: /srv/web
    command: yarn dev:next
    env_file:
      - ./.env
    labels:
      - 'traefik.http.routers.frontend.rule=Host(`portfolio.localhost`)'
